In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
credit_card_data = pd.read_csv('creditcard.csv')

In [3]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [11]:
credit_card_data[credit_card_data['Class'] == 1]

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
623,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1
4920,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1
6108,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1
6329,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [8]:
credit_card_data[credit_card_data['Class'] == 0].head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [12]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [13]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [14]:
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [15]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data['Class'] == 1]

In [16]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [17]:
legit['Amount'].describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [18]:
fraud['Amount'].describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [19]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [20]:
legit_sample = legit.sample(n = 492)

In [21]:
new_dataset = pd.concat([legit_sample, fraud], axis = 0)

In [22]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
225022,144067.0,-0.503415,0.512794,-2.806978,-0.438521,1.022610,-1.082492,1.971757,-0.171762,-0.346419,...,0.399918,1.433065,0.450270,-1.009992,-0.933472,0.472630,0.373837,0.208451,173.02,0
185475,126682.0,1.992819,0.133886,-1.726361,0.561500,0.148101,-1.511387,0.341751,-0.424798,0.535387,...,0.220159,0.753324,-0.052626,-0.006441,0.251358,-0.108683,-0.006402,-0.024521,36.63,0
6017,6756.0,1.047797,0.034117,1.611696,2.043393,-0.818484,0.354826,-0.556535,0.119177,2.368760,...,-0.521577,-0.734918,0.152062,0.563898,0.361037,-0.583511,0.071240,0.029297,9.58,0
58664,48494.0,-2.445611,-6.616814,-1.159859,0.358956,-3.393523,-0.430185,1.882168,-0.580088,1.702223,...,1.294918,-0.344908,-1.751919,0.884977,-0.254515,-0.127688,-0.313680,0.359871,1916.00,0
55006,46727.0,-1.305192,0.734365,1.302977,-1.857413,-0.487454,-0.085386,-0.998421,-2.177378,-1.054561,...,2.389437,-0.649861,0.066415,-0.145799,-0.086290,-0.458291,0.255599,0.116757,15.46,0

In [23]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [24]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [25]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,97512.030488,0.082328,0.005454,0.089765,-0.148731,-0.030292,0.015958,-0.009950,0.084186,0.079530,...,0.010355,0.022362,0.001654,0.002054,-0.009056,-0.010907,0.034421,0.011367,0.005125,81.038862
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [26]:
X = new_dataset.drop(columns = 'Class' , axis = 1)
Y = new_dataset['Class']

In [27]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
225022  144067.0 -0.503415  0.512794 -2.806978 -0.438521  1.022610 -1.082492
185475  126682.0  1.992819  0.133886 -1.726361  0.561500  0.148101 -1.511387
6017      6756.0  1.047797  0.034117  1.611696  2.043393 -0.818484  0.354826
58664    48494.0 -2.445611 -6.616814 -1.159859  0.358956 -3.393523 -0.430185
55006    46727.0 -1.305192  0.734365  1.302977 -1.857413 -0.487454 -0.085386
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
225022  1.971757 -0.171762 -0.346419  ... -0.384732  0.399918  1.433065
185475  0.341751 -0.424798  0.535387  ... -0.117558  0.220159  0.753324
6017   -0.556535  0.119177  2.368760  ... -0.216605 -0.521577 -0.734918
58664   1.882168 -0.580088  1.702223  ...  3.803005  1.294918 -0.344908
55006  -0.998421 -2.177378 -1.054561  ... -0.547454  2.389437 -0.649861
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28   Amount
225022  0.450270 -1.009992 -0.933472  0.472630  0.373837  0.208451   173.02
185475 -0.052626 -0.006441  0.251358 -0.108683 -0.006402 -0.024521    36.63
6017    0.152062  0.563898  0.361037 -0.583511  0.071240  0.029297     9.58
58664  -1.751919  0.884977 -0.254515 -0.127688 -0.313680  0.359871  1916.00
55006   0.066415 -0.145799 -0.086290 -0.458291  0.255599  0.116757    15.46
...          ...       ...       ...       ...       ...       ...      ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968   390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637     0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361    77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700   245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309    42.53

[984 rows x 30 columns]

In [28]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2)

In [40]:
X_train

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
100623,67571.0,-0.758469,-0.045410,-0.168438,-1.313275,-1.901763,0.739433,3.071892,-0.483422,0.618203,...,-0.032500,0.042619,0.397224,0.072229,-0.242276,0.560916,-0.540955,0.150606,-0.117140,549.06
248180,153824.0,2.053782,-0.260180,-1.557341,0.187745,0.477483,0.085766,-0.038692,-0.063850,0.520956,...,-0.127886,0.140625,0.662121,-0.066402,0.196228,0.293853,0.708957,-0.075660,-0.078997,11.50
281672,170347.0,-1.375801,2.073836,-1.649878,-1.449257,0.816406,-1.172043,1.144346,0.185882,0.035826,...,0.332632,0.233753,0.861085,-0.106864,0.788544,-0.119312,0.041043,0.541138,0.441724,1.44
63847,50891.0,-1.113342,1.135719,3.078471,2.617967,-0.735346,0.546227,-0.360581,0.356379,-0.334812,...,0.519132,0.170145,0.828364,-0.251574,0.506966,-0.025769,0.370681,0.407483,0.087034,5.67
258215,158547.0,1.997334,-1.244921,-0.534142,-0.911475,-1.161407,-0.370941,-1.007176,0.045863,-0.057375,...,0.088825,0.022599,-0.147647,0.280038,-0.378493,-0.536017,-0.490128,-0.009627,-0.042286,83.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233007,147405.0,1.612545,-0.787673,-2.163337,0.543794,-0.032639,-0.777613,0.212062,-0.109075,1.345736,...,0.160713,-0.165181,-0.863727,0.026106,0.395520,-0.177702,-0.128074,-0.067284,0.020772,232.52
281063,169913.0,-0.862739,1.838888,-1.233258,-0.713979,0.677185,-0.503230,0.562750,0.413854,-0.056975,...,0.234946,0.325652,1.305684,-0.089962,0.249180,-0.531335,-0.236802,0.314591,0.099946,0.89
223618,143456.0,-2.006582,3.676577,-5.463811,7.232058,-1.627859,-0.996755,-4.299833,2.268867,-3.651067,...,0.474414,0.713907,-0.063868,0.167947,-0.449864,0.023702,0.536905,0.485864,-0.042393,1.00
43061,41353.0,-15.020981,8.075240,-16.298091,5.664820,-11.918153,-4.246957,-14.716668,9.435084,-6.795398,...,-0.995787,2.525115,-0.832074,-0.186117,0.429781,0.697103,0.056031,-1.310888,-0.707403,34.12
676,511.0,-0.556245,0.657574,2.706193,2.792656,0.208496,0.908663,0.074210,0.065530,-0.757281,...,0.416085,0.105614,0.489549,-0.328685,-0.427097,0.207280,0.413055,-0.058339,-0.125352,37.96

In [41]:
Y_train

100623    1
248180    0
281672    0
63847     0
258215    0
         ..
233007    0
281063    0
223618    1
43061     1
676       0
Name: Class, Length: 787, dtype: int64

In [42]:
X_test

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
247995,153761.0,1.146259,1.403458,-4.159148,2.660107,-0.323217,-1.836071,-1.623740,0.259562,-1.132044,...,0.284831,0.564450,0.445744,-0.141136,-0.265517,0.362260,-0.416062,0.507370,0.243744,51.37
141981,84543.0,1.156908,-0.383048,-0.340135,0.186093,1.517642,4.068000,-1.106330,1.084110,0.758268,...,0.043260,-0.099680,-0.293047,-0.063401,1.002396,0.564154,-0.396381,0.069739,0.036090,35.97
126706,78064.0,-1.835972,1.590035,0.822742,-1.580636,-0.615626,-0.531703,0.110797,0.531271,0.875271,...,0.526342,-0.184934,-0.155076,0.083366,0.224307,-0.159294,0.721666,0.427246,0.069756,8.45
87800,61849.0,1.229107,0.220425,0.164865,0.510481,-0.231805,-0.576521,-0.077039,0.012786,-0.073917,...,-0.106673,-0.265546,-0.851656,0.082744,-0.065952,0.199948,0.100157,-0.033677,0.016049,5.49
15451,26833.0,-20.532751,12.373989,-23.009003,6.144821,-15.587296,-4.384491,-15.939003,13.696416,-3.948455,...,1.592754,1.754608,-1.466115,-0.856779,0.125777,1.402587,-0.223755,1.574249,0.469201,99.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108258,70828.0,0.196707,1.189757,0.704882,2.891388,0.045555,1.245730,-1.198714,-2.421616,-1.232089,...,0.646616,-1.328132,0.189311,-0.005524,-0.814708,0.400924,0.286281,0.135215,0.257315,0.76
12108,21046.0,-16.917468,9.669900,-23.736443,11.824990,-9.830548,-2.514829,-17.290657,1.820408,-6.264903,...,0.996745,-2.336111,0.972755,1.241866,-1.051086,0.038009,0.672317,2.108471,-1.421243,1.00
99506,67150.0,-1.824295,0.403327,-1.994122,2.756558,-3.139064,0.408185,-1.209045,1.095634,-1.447225,...,1.503688,0.838760,0.341727,0.947506,-0.145493,0.049326,0.831065,0.332421,0.252713,489.71
74496,55614.0,-7.347955,2.397041,-7.572356,5.177819,-2.854838,-1.795239,-8.783235,0.437157,-3.740598,...,0.073164,-0.175273,0.543325,-0.547955,-0.503722,-0.310933,-0.163986,1.197895,0.378187,0.83
169263,119604.0,-1.619294,-0.151724,1.486068,-0.452833,1.141673,-0.294449,-0.015996,0.099285,0.353764,...,-0.011028,-0.290299,-0.622188,-0.491543,-1.066426,0.443493,-0.324138,0.369802,0.047155,73.22

In [43]:
Y_test

247995    1
141981    0
126706    0
87800     0
15451     1
         ..
108258    1
12108     1
99506     1
74496     1
169263    0
Name: Class, Length: 197, dtype: int64

In [29]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [30]:
model = LogisticRegression()

In [31]:
model.fit(X_train, Y_train)

LogisticRegression()

In [36]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [33]:
print(training_data_accuracy)

0.9504447268106735

In [37]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [39]:
print(test_data_accuracy)

0.9390862944162437